### ISSUE TITLE
Set.globalID is not uniquely assigned

### ISSUE THREAD

**Issue by rileyvickers** [tmweigand/PMMoTo#13]
Checking with the gatherSetData we wrote yesterday, there are repeats of globalID, see attached csv of all setData

row 1 is arbitrary information
col 1 is array index of set information in setData
col 2 is globalID of set in setData, note the early repeats

Based on number of repeats, might have something to do with boundary behavior, i.e. multiple processors are adding info for shared sets?

Investigating now, can talk later today, may make some changes to sets.pyx
[setData.csv](https://github.com/tmweigand/PMMoTo/files/10885138/setData.csv)

**Comment by tmweigand** [comment]
That is correct. The localID is unique but the globalID is not. The globalID connect sets across multiple subDomains. I think what you want to do is merge the golbalConnectedSets for the duplicated globalIDs.

**Comment by tmweigand** [comment]
Minor correction, localID is unique only on a processor level.

**Comment by rileyvickers** [comment]
Ohh I see, looking at globalconnected this is tracking with the latter of the statements from the previous comment. 

Entries of globalConnectedSets are identical, just occasionally reordered. Will confirm this is the case and then pick the correct option based on whether a merge is needed or a deletion of the repeats is sufficient
