### ISSUE TITLE
globalConnectedSets, not connecting correctly for boundary

### ISSUE THREAD

**Issue by rileyvickers** [tmweigand/PMMoTo#16]
When searching through the MA, not all sets are connected to neighbors, even if they appear adjacent.

See attached folder with dataOut. Variable globalPathID in this case is representing a 'visited' flag from the search of the MA. One side of the sets split by the boundary are not on other sets neighbor lists and are thus not visited in the search.

This behavior occurs regardless of method chosen for keeping/merging neighbor lists when gathering set information to root.

Problem identified when attempting to set a true globalPathID based on DFS of MA sets, in which these same non-visited sets were not correctly displaying the globalPathID of neighbors. 
[dataOut.zip](https://github.com/tmweigand/PMMoTo/files/10936163/dataOut.zip)

**Comment by tmweigand** [comment]
Is the visited flag set on a subDomain basis or globally?

**Comment by rileyvickers** [comment]
globally, during the search through the combined list of sets gathered to root

**Comment by tmweigand** [comment]
My guess then is that it is related to having duplicate globalIDs but unique (on a subDomain level) localIDs.

**Comment by rileyvickers** [comment]
Problem resolved. Issue was with my handling of scattering information back to all subprocesses, accidentally overwrote the  rank identification, leading to failure to update the set information.
