### ISSUE TITLE
Data Output 

### ISSUE THREAD

**Issue by kbruning** [tmweigand/PMMoTo#23]
When saving set data in equilibriumFluidDistribution.pyx, approx. line 155, I get an error in dataOutput.py around line 183 when the number of procsWithSets < Domain.numSubDomains due to the name list not having enough entries. Changing the for loop to only run through the number of procs with sets will result in an error in the following addPiece fxn. Changing the length of the name list to the total number of subdomains will run, but will not be able to be opened in Paraview.

I am on the timMA branch and running testDrainImb.py at 101^3 nodes, all other parameters as they are in the current commit.

**Comment by tmweigand** [comment]
@kbruning Fixed.
