### ISSUE TITLE
EDT always 0 at x = 0

### ISSUE THREAD

**Issue by kbruning** [tmweigand/PMMoTo#27]
EDT is always zero at x = 0 when running testInkBottle.py with the following changes to the current commit: nodes = [140,30,30], wRes = [[0,1],[0,0],[0,0]], and nRes = [[1,0],[0,0],[0,0]]. This was true for both pc cases I tested, pc = 1.81122 and pc = 3.41274.

**Comment by tmweigand** [comment]
Issue was with processing data. Added flag to remove halos when saving as csv data.
