### ISSUE TITLE
RemoveHalo = False

### ISSUE THREAD

**Issue by kbruning** [tmweigand/PMMoTo#33]
I am trying to output what is occurring in the reservoirs at multiple steps within calcDrainage. When I set removeHalo to False, the csv outputs of x,y,z,value are all 0's. This is happening for testInkBottle at pc = 1.81122 for reservoir sizes of 1 and 10 voxels. Setting removeHalo to True outputs the csv populated as expected.

**Comment by tmweigand** [comment]
Found a typo and pushed to timMA. If that did not fix it, I will look into it more later.

**Comment by kbruning** [comment]
Fixed!
