### ISSUE TITLE
Save to single csv

### ISSUE THREAD

**Issue by kbruning** [tmweigand/PMMoTo#35]
Could an additional function be created within dataOutput.py to save the grid as a single csv without halos?

**Comment by tmweigand** [comment]
To do this, all the data would have to be passed to a single process which will be slow and potentially crash the machine. I suggest we do this as a post-PMMoTo step where we write multiple csvs without halos and concatenate them. 

Alternatively, I can send code on how to read the vtk files.

**Comment by kbruning** [comment]
Okay thanks for the suggestion, I can take care of writing this. I am working on converting the PMMoTo outputs to a LBM input.
