### ISSUE TITLE
Minkowski Definitions

### ISSUE THREAD

**Issue by tmweigand** [tmweigand/PMMoTo#47]
@rileyvickers @ajotcham Do any of you two have a preference for how we define the Minkowski functionals? I think I prefer the definitions in this [article](https://github.com/tmweigand/PMMoTo/files/14440403/Armstrong_McClure_etal_19.pdf) vs those in [quantimpy](https://www.softxjournal.com/article/S2352-7110(21)00115-1/fulltext). Cool if I switch it?

**Comment by rileyvickers** [comment]
I like the Armstrong paper a lot. Many more citations and the quantimpy pub also cites them, so I think using the Armstrong defs are the more standard ones. Seems good to me.

**Comment by tmweigand** [comment]
Cool.
